version: '3.8'

services:
  searx:
    image: searxng/searxng:latest
    container_name: searx-ai-8080
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
      - SEARXNG_SECRET=ai-search-secret-8080
    volumes:
      - searx-data-8080:/etc/searxng
    restart: unless-stopped
    networks:
      - searx-network-8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  searx-data-8080:

networks:
  searx-network-8080:
    driver: bridge
