services:
  searx:
    image: searxng/searxng:latest
    container_name: ai_searx
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080
      - SEARXNG_SECRET_KEY=ai_search_secret_key_2025
    volumes:
      - ./searx-config:/etc/searxng:rw
      - ./searx-data:/var/lib/searxng:rw
    restart: unless-stopped
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge
