[project]
name = "futureai"
version = "0.1.0"
description = "AGI/ASI AI project with Google Gemini 2.0 Flash"
requires-python = ">=3.8"
dependencies = [
    "flask",
    "flask-compress",
    "requests"
]